{% set name = "sphinx-astropy" %}
{% set version = "1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-astropy-{{ version }}.tar.gz
  sha256: 2bd33bc2fb1a2a8cee4f10fd1ea6642ddfad66ab133d60f2e96dff44bfd22bc5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - astropy-sphinx-theme
    - numpydoc
    - pillow
    - sphinx >=1.7
    - sphinx-automodapi
    - sphinx-gallery

test:
  imports:
    - sphinx
    - astropy_sphinx_theme
    - numpydoc
    - sphinx_astropy
    - sphinx_automodapi
    - sphinx_gallery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.astropy.org
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Sphinx extensions and configuration specific to the Astropy project
  description: |
    This package serves two purposes: it provides a default Sphinx configuration
    and set of extensions specific to the Astropy project, and it acts as a
    meta-package by installing all required Sphinx extensions for the core
    Astropy package and other packages.
  doc_url: https://github.com/astropy/sphinx-astropy
  dev_url: https://github.com/astropy/sphinx-astropy

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
